### ISSUE TITLE
How to use this tool?

### ISSUE THREAD

**Issue by SalviaSage** [dail8859/github-release-history#3]
Hi. I am interested in using this tool.
But I do not know how, you say to do a pull request or a new issue, but for what?

To this repository? Can you change the explanation to be more detailed please?

Thanks.

**Comment by dail8859** [comment]
There is a file in this repository that contains a list of repositories. The android app in the repo was installed on my phone and once a day would fetch the file, request the download count, then upload the statistics. That would then be used to display results in a browser.

Currently this project is dead as far as I'm concerned (and I should update readme to reflect that). I got rid of my development machine a while ago and have no time nor desire to install Android Studio again just to get the app back on my phone.

That being said if someone had interest in the project they could set it up on their phone and use their own repo to start saving daily statistics.

**Comment by SalviaSage** [comment]
Do you need the android app to use this? I don't have an adroid phone.
I use Win10.

**Comment by dail8859** [comment]
No it doesn't have to use the Android app. **However** new software would have to be written that replaces it.

Since my Android phone was the only Internet-enabled device that is connected 24/7 I decided to create an app for it (and plus I had never created one before and wanted to learn how).

I'm sure it would be possible to do the same thing with something like Python but it would have to be automated to run every 24 hours to request the current download count for the repositories, then commit/push the changes back to GitHub.

**Comment by SalviaSage** [comment]
So I guess this thing is unusable then...

It is a good idea though, as this way an author can judge the popularity of his releases.

Thanks for the replies, and bye.

**Comment by dail8859** [comment]
That's exactly why I created it so I could see how often my software releases were downloaded. If I had a reason to have Android Studio installed I would use it...but it's not worth the effort or harddrive space just for this one simple app.

**Comment by dail8859** [comment]
@SalviaSage 

Some things have changed and I now have a device online 24/7 so I decided to rewrite the logic I had for the Android app and just write it in Python. So if you are still interested in using this tool then I think it should be collecting statistics now.

You simply need to modify the [repos.json](https://github.com/dail8859/github-release-history/blob/master/repos.json) file with the username and repository name that you want to track, then check back in a week or so.

**Comment by SalviaSage** [comment]
Oh wow, nice news.

Can you please give an example of it working perhaps from one of your own repositories such as lua script.

And some more details on how to set it up.

Thanks!

**Comment by dail8859** [comment]
Here's an example for LuaScript:

https://dail8859.github.io/github-release-history/index.html?username=dail8859&repository=LuaScript

The past few days is not valid data so it doesn't show any change at all yet. Now that the script is set up to run once a day then it should be collecting valid download counts from now on.

> And some more details on how to set it up.

You mean for you to track downloads yourself?

**Comment by SalviaSage** [comment]
Yeah. Your repo looks good and set up.
But if I try a repo of my own I get
"That repository hasn't been set up to have the download count tracked yet."

So, all I would ask is that you update your documentation main page for example, so people who are interested know what to do to set up their own download counter.

This feature can hopefully be here in this very amazing coding-community site called github.
This place is home.  ^_^

**Comment by dail8859** [comment]
> But if I try a repo of my own I get
"That repository hasn't been set up to have the download count tracked yet."

Correct. To start tracking a repository it is as simple as I stated both in this issue and in the documentation. The repos.json file needs updated with any repositories to track. That's it. If you look at that file you'll notice that there are other repositories in there other than my own that are tracked.

If you want a detailed technical description of what happens behind the scene I can also explain that if it would help.

**Comment by SalviaSage** [comment]
If it's not much to ask, can you also open a folder for me like you have for other users
and put a .json file in there?

This is the repo that I want to track
https://github.com/SalviaSage/Translingual-Phonetic-Alphabet/releases

Thanks.

**Comment by dail8859** [comment]
Not a problem at all. Committed as f07b854d3c303fd494513ea807793f88a880ffd3

It fetches the download count once a day so after a few days it will have enough data points to start graphing it on the website.

**Comment by SalviaSage** [comment]
Thanks.
